### ISSUE TITLE
Wrong config example in README: `timeout`

### ISSUE THREAD

**Issue by Xuhao** [aamine/activerecord4-redshift-adapter#29]
There is `timeout` config in config example, but it looks it won't be used, flow this line:

https://github.com/aamine/activerecord4-redshift-adapter/blob/1b17aa7980eabe14bb393648949f5e2e46722c4f/lib/active_record/connection_adapters/redshift_adapter.rb#L23

`timeout` is not a valid config so.

I think it should be `connect_timeout` or `variables:statement_timeout`:

```yaml
development:
  adapter: redshift
  host: your_cluster_name.hashhash.ap-northeast-1.redshift.amazonaws.com
  port: 5439
  database: dev
  username: your_user
  password: your_password
  encoding: utf8
  pool: 3
  connect_timeout: 5000
  variables:
    statement_timeout: 5000
```
